fix putit

diff --git a/bin/putit b/bin/putit
--- a/bin/putit
+++ b/bin/putit
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-msg=${1:-commit}
+if test -z "${1}" ; then
+  echo "Error: commit message"
+  exit 1
+fi
+
+msg="${1}"
 
 git add .
 git commit -a -m "${msg}"
